/-!
{
  "name": "numpy.testing.assert_string_equal",
  "category": "Assertion Functions",
  "description": "Test if two strings are equal",
  "url": "https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_string_equal.html",
  "doc": "Test if two strings are equal.\n\nIf the given strings are equal, \`assert_string_equal\` does nothing. If they are not equal, an AssertionError is raised, and the diff between the strings is shown.",
  "code": "def assert_string_equal(actual, desired):\n    \"\"\"\n    Test if two strings are equal.\n\n    If the given strings are equal, \`assert_string_equal\` does nothing.\n    If they are not equal, an AssertionError is raised, and the diff\n    between the strings is shown.\n\n    Parameters\n    ----------\n    actual : str\n        The string to test for equality against the expected string.\n    desired : str\n        The expected string.\n\n    Examples\n    --------\n    >>> np.testing.assert_string_equal('abc', 'abc')\n    >>> np.testing.assert_string_equal('abc', 'abcd')\n    Traceback (most recent call last):\n      File \"<stdin>\", line 1, in <module>\n    ...\n    AssertionError: Differences in strings:\n    - abc+ abcd?    +\n\n    \"\"\"\n    # delay import of difflib to reduce startup time\n    __tracebackhide__ = True  # Hide traceback for py.test\n    import difflib\n\n    if not isinstance(actual, str):\n        raise AssertionError(repr(type(actual)))\n    if not isinstance(desired, str):\n        raise AssertionError(repr(type(desired)))\n    if desired == actual:\n        return\n\n    diff = list(difflib.Differ().compare(actual.splitlines(True),\n                                         desired.splitlines(True)))\n    diff_list = []\n    while diff:\n        d1 = diff.pop(0)\n        if d1.startswith('  '):\n            continue\n        if d1.startswith('- '):\n            l = [d1]\n            d2 = diff.pop(0)\n            if d2.startswith('? '):\n                l.append(d2)\n                d3 = diff.pop(0)\n                if d3.startswith('+ '):\n                    l.append(d3)\n                    d4 = diff.pop(0)\n                    if d4.startswith('? '):\n                        l.append(d4)\n                    else:\n                        diff.insert(0, d4)\n                else:\n                    diff.insert(0, d3)\n            else:\n                diff.insert(0, d2)\n            diff_list.extend(l)\n        if d1.startswith('+ '):\n            diff_list.append(d1)\n            d2 = diff.pop(0)\n            if d2.startswith('? '):\n                diff_list.append(d2)\n            else:\n                diff.insert(0, d2)\n    if not diff_list:\n        return\n    msg = f\"Differences in strings:\\n{''.join(diff_list).rstrip()}\"\n    raise AssertionError(msg)"
}
-/

-- TODO: Implement assert_string_equal
