name: Claude Assistant

on:
  pull_request_target:
    types: [opened, synchronize]
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  claude-assist:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.body, '@claude'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Claude Response
      uses: anthropics/claude-code-action@beta
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        anthropic_model: claude-opus-4-20250514
        max_turns: 5
        timeout_minutes: 10
        custom_instructions: |
          You are Claude, an AI assistant helping with the vericoding repository.
          This repository contains tools and benchmarks for verified coding using:
          - Lean 4 for formal verification
          - Dafny for verified programming
          - Verus for verified Rust
          
          When responding to questions:
          - Provide clear, helpful answers about verification techniques
          - Suggest appropriate verification tools for the task
          - Include code examples when relevant
          - Reference existing examples in the repository when applicable
