name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: write      # Ability to manage GitHub Actions
      checks: write       # Ability to create and update check runs
      statuses: write     # Ability to update commit statuses
      discussions: write  # Ability to manage discussions
      packages: write     # Ability to manage packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          model: "claude-opus-4-1"
          additional_permissions: |
            actions: "read"
          prompt: |
            REPO: ${{github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            Please review this pull request and try to make it better.
          
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: |
            --dangerously-skip-permissions
            --allowedTools Bash,Read,Grep,Glob,LS,TodoRead,MultiEdit,Edit
            --model claude-opus-4-1
            --mcp-config '{"mcpServers": { "lean-lsp-mcp": { "command": "uvx", "args": ["lean-lsp-mcp"]}}}'
          

