name: Dafny Syntax Validation

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate-dafny:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
        
    - name: Install Dafny
      uses: dafny-lang/setup-dafny-action@v1
      with:
        dafny-version: "4.10.0"
        
    - name: Convert YAML files and validate with Dafny
      run: |
        set -e  # Exit on any error
        
        # Process each YAML file (robust against spaces in filenames)
        yaml_count=0
        while IFS= read -r -d '' yaml_file; do
          yaml_count=$((yaml_count + 1))
          echo "Processing: $yaml_file"
          
          # Convert YAML to .dfy
          python src/convert_from_yaml.py "$yaml_file" --suffix dfy
          
          # Get the corresponding .dfy file path
          dfy_file="${yaml_file%.yaml}.dfy"
          
          # Run dafny resolve on the generated file
          echo "Running dafny resolve on: $dfy_file"
          dafny resolve "$dfy_file"
          
          echo "✓ Successfully validated syntax: $dfy_file"
        done < <(find benchmarks/vericoding_raw/dafnybench -name "*.yaml" -type f -print0)
        
        if [ $yaml_count -eq 0 ]; then
          echo "No YAML files found in benchmarks/vericoding_raw/dafnybench"
          exit 1
        fi
        
        echo "All $yaml_count Dafny files validated successfully!"
