name: Python Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - "spec_to_code.py"
      - ".github/workflows/python-quality.yml"
  pull_request:
    branches: [ main, develop ]
    paths:
      - "spec_to_code.py"
      - ".github/workflows/python-quality.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Run Ruff (linter)
      run: |
        echo "::group::Ruff Linting spec_to_code.py"
        ruff check spec_to_code.py --output-format=github
        echo "::endgroup::"

    - name: Run Ruff (formatter check)
      run: |
        echo "::group::Ruff Format Check spec_to_code.py"
        ruff format --check spec_to_code.py
        echo "::endgroup::"
