name: Python Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - "vericoder.py"
      - "vericoding/**/*.py"
      - ".github/workflows/python-quality.yml"
  pull_request:
    branches: [ main, develop ]
    paths:
      - "vericoder.py"
      - "vericoding/**/*.py"
      - ".github/workflows/python-quality.yml"
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: uv sync --no-install-project

    - name: Run Ruff linter
      uses: astral-sh/ruff-action@v3
      with:
        src: "./vericoding ./vericoder.py"
        args: "check --output-format=github"

    - name: Check code formatting with Ruff
      uses: astral-sh/ruff-action@v3
      with:
        src: "./vericoding ./vericoder.py"
        args: "format --check"
