name: Python Code Quality

on:
  push:
    branches: [ main, develop ]
    paths:
      - "spec_to_code.py"
      - ".github/workflows/python-quality.yml"
  pull_request:
    branches: [ main, develop ]
    paths:
      - "spec_to_code.py"
      - ".github/workflows/python-quality.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Set up Python
      run: uv python install 3.12

    - name: Install and run Ruff (linter)
      uses: astral-sh/ruff-action@v3
      with:
        src: "spec_to_code.py"
        args: "check --output-format=github"

    - name: Install and run Ruff (formatter check)
      uses: astral-sh/ruff-action@v3
      with:
        src: "spec_to_code.py"
        args: "format --check"
