name: Run a few python tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  a-few-python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python
      run: uv python install
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run tests
      run: uv run pytest src/tests/test_apply_json_replacements.py src/tests/test_cheat_checker.py  src/tests/test_placeholder_counting.py -v
