name: Test Conversion Consistency - Verus

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-conversion-consistency-verus:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Install dependencies
      run: uv sync
      
    - name: Make test script executable
      run: chmod +x test_conversion_consistency.sh
      
    - name: Run conversion consistency tests for Verus
      run: ./test_conversion_consistency.sh rs benchmarks/verus/dafnybench
      
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-verus
        path: |
          benchmarks/
          test_conversion_consistency.sh
        retention-days: 7