name: Test Rust to YAML Converter

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Set up Python
      run: uv python install
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run Rust to YAML converter tests
      run: uv run src/tests/test_rust_to_yaml.py
