# Fast Configuration for QA Metadata Generation
# This configuration prioritizes speed over precision

# Similarity Analysis - Fast Vector Embeddings
similarity:
  method: "optimized_vector"
  
  # More lenient similarity threshold for faster processing
  threshold: 0.80
  
  # Semantic focus for fastest processing
  embedding_focus: "semantic"
  
  # Fastest embedding model
  embedding_model: "all-MiniLM-L6-v2"
  
  # Performance settings optimized for speed
  max_examples: 3          # Fewer examples for faster processing
  cache_dir: ".fast_vector_cache"  # Separate cache for fast embeddings
  batch_size: 64           # Larger batches for speed
  use_gpu: false           # Set to true if CUDA is available for even more speed

# Scoring System - More Lenient for Development/Testing
scoring:
  # Use proportional base score like default config
  base_score_mode: "proportional"
  proportional_points_per_entry: 0.5
  proportional_max_score: 500
  proportional_min_score: 50
  
  # Verus - very lenient penalties for development (optimized)
  verus:
    specs_with_default_values_penalty: 3    # Very low penalty for development
    execs_with_bodies_penalty: 8            # Reduced penalty for development
    execs_with_ghost_types_penalty: 0.2     # Minimal penalty for ghost types
    near_duplicates_penalty: 1              # Very low penalty for duplicates
  
  # Dafny - lenient penalties for development (optimized)
  dafny:
    functions_with_default_values_penalty: 3   # Very low penalty for development
    methods_with_bodies_penalty: 8            # Reduced penalty for development
    near_duplicates_penalty: 1                # Very low penalty for duplicates
  
  # Lean - lenient penalties for development (optimized)
  lean:
    definitions_with_sorry_penalty: 8         # Reduced penalty for development
    near_duplicates_penalty: 1               # Very low penalty for duplicates

# Quality Analysis Script Configuration
qa_scripts:
  script_timeout: 120      # Shorter timeout for speed
  include_problematic_dirs: false
  output_format: "json"

# Logging Configuration
logging:
  level: "warning"         # Minimal logging for speed
  show_progress: false     # No progress bars for fastest execution
