# High Quality Configuration for QA Metadata Generation
# This configuration prioritizes accuracy over speed

# Similarity Analysis - High Quality Vector Embeddings
similarity:
  method: "optimized_vector"
  
  # More strict similarity threshold for higher precision
  threshold: 0.90
  
  # Balanced focus for comprehensive comparison
  embedding_focus: "balanced"
  
  # Higher quality embedding model (slower but more accurate)
  embedding_model: "all-mpnet-base-v2"
  
  # Performance settings optimized for quality
  max_examples: 10         # More examples for better analysis
  cache_dir: ".hq_vector_cache"  # Separate cache for high-quality embeddings
  batch_size: 16           # Smaller batches for stability
  use_gpu: false           # Set to true if CUDA is available

# Scoring System - More Strict Quality Requirements
scoring:
  # Use proportional base score like default config
  base_score_mode: "proportional"
  proportional_points_per_entry: 0.5
  proportional_max_score: 500
  proportional_min_score: 50
  
  # Verus - stricter penalties for production quality (optimized)
  verus:
    specs_with_default_values_penalty: 8     # Higher penalty for defaults (but balanced)
    execs_with_bodies_penalty: 18           # Strong penalty for implementations
    execs_with_ghost_types_penalty: 1       # Minimal but present penalty for ghost types
    near_duplicates_penalty: 4              # Higher penalty for duplicates
  
  # Dafny - strict requirements for production (optimized)
  dafny:
    functions_with_default_values_penalty: 8   # Higher penalty for defaults (but balanced)
    methods_with_bodies_penalty: 18           # Strong penalty for implementations
    near_duplicates_penalty: 4                # Higher penalty for duplicates
  
  # Lean - strict requirements for production (optimized)
  lean:
    definitions_with_sorry_penalty: 18        # Strong penalty for sorry (but balanced)
    near_duplicates_penalty: 4               # Higher penalty for duplicates

# Quality Analysis Script Configuration
qa_scripts:
  script_timeout: 600      # Longer timeout for thorough analysis
  include_problematic_dirs: false  # Exclude problematic directories
  output_format: "json"

# Logging Configuration
logging:
  level: "info"
  show_progress: true
